spring:
  data:
    mongodb:
      uri: mongodb://ISIS2304A33202320:aKrSFgLJapER@157.253.236.88:8087/ISIS2304A33202320
      database: ISIS2304A33202320

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
